version: '3'

services:
  livepeer:
    image: livepool/go-livepool:llm
    networks:
      - hive-gateway-network
    volumes:
      - ./lpData:/root/.lpData/keystore
    command: >
      livepeer -gateway -mainnet -httpAddr 0.0.0.0:8935 -httpIngest -v 6 -ethPassword /root/.lpData/password.txt

  api:
    image: livepool/openai-api:latest
    networks:
      - hive-gateway-network
    depends_on:
      - livepeer
    command: --gateway http://livepeer:8935

  nginx:
    image: nginx:alpine
    networks:
      - hive-gateway-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

networks:
  hive-gateway-network:
    driver: bridge
