services:
  livepeer:
    image: livepeer/go-livepeer:v0.7.9-ai.2
    networks:
      - chatlpt-network
    volumes:
      - ./lpData:/root/.lpData/
    command: '-config /root/.lpData/livepeer.conf'

  api:
    image: livepool/openai-api:llm
    networks:
      - chatlpt-network
    depends_on:
      - livepeer
    command: --gateway http://livepeer:8935

  nginx:
    image: nginx:alpine
    networks:
      - chatlpt-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

networks:
  chatlpt-network:
    driver: bridge
